# Generated by Django 3.2 on 2021-05-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_ecosoft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyitem',
            name='record_date',
            field=models.DateTimeField(),
        ),
    ]
