# Generated by Django 3.2 on 2021-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_ecosoft', '0002_alter_scrapyitem_record_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, null=True)),
                ('trading', models.CharField(max_length=100, null=True)),
                ('cat', models.CharField(max_length=100, null=True)),
                ('ltp', models.CharField(max_length=100, null=True)),
                ('change_persent', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('trade', models.CharField(max_length=100, null=True)),
                ('high', models.CharField(max_length=100, null=True)),
                ('low', models.CharField(max_length=100, null=True)),
                ('open', models.CharField(max_length=100, null=True)),
                ('ycp', models.CharField(max_length=100, null=True)),
                ('pe', models.CharField(max_length=100, null=True)),
                ('spot', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
                ('record_date', models.DateTimeField()),
                ('dividend', models.CharField(max_length=100, null=True)),
                ('analysis', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
