# Generated by Django 3.2 on 2021-05-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_ecosoft', '0004_scrapyitemmodel_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapyitemmodel',
            old_name='analysis',
            new_name='trade_code',
        ),
        migrations.RemoveField(
            model_name='scrapyitemmodel',
            name='dividend',
        ),
        migrations.RemoveField(
            model_name='scrapyitemmodel',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='scrapyitemmodel',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='scrapyitemmodel',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='scrapyitemmodel',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='scrapyitemmodel',
            name='trading',
        ),
    ]
